logging:
  level:
    root: ERROR
    org:
      springframework:
        web: INFO
      hibernate: ERROR

spring:
  main:
      banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cloud_native_app_db
    username: cloud_user
    password: pass@123
    hikari:
      connection-timeout: 5000 #5 secs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      continue-on-error: true