logging:
  level:
    root: ERROR
    com:
      csye6225:
        cloud: DEBUG
    org:
      springframework:
        web: ERROR
      hibernate: ERROR

spring:
  profiles:
    default: local
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  main:
      banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000 #5 secs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false